import matplotlib.pyplot as plt
import numpy as np
import argparse
import ltspice
import sys
import os

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="LTSpice Graph Generator")
    parser.add_argument('raw_file', metavar='file_path', type=str, nargs=1,
                        help="RAW File generated by LTSpice")
    parser.add_argument('graph_file', metavar='graph_path', type=str, nargs=1,
                        help="Graph file to be plot to")                    
    parser.add_argument('values', metavar='exprs', type=str, nargs='+',
                        help="Expresions to be ploted")

    args = parser.parse_args()
    
    if(not os.path.exists(args.raw_file)):
        print('invalid raw file: file not find!',file=sys.stderr)

    raw = ltspice.Ltspice(args.raw_file)
    raw.parse()

    pass
